Updated with new search engine
trimstray/the-book-of-secret-knowledge pull request #195
Opened 2021-01-22 13:30 UTC by Luci-d

Spyse.com is in-line with shodan and censys IMO.

P.S. This is the best tools repository. Very thanks.

2021-02-19 23:55 UTC, hackerorya commented
Hacking tools

2021-02-19 23:56 UTC, hackerorya commented on README.md
>  &nbsp;&nbsp;:small_orange_diamond: <a href="https://2000.shodan.io/#/"><b>Shodan 2000</b></a> - do you use Shodan for everyday work? This tool looks for randomly generated data from Shodan.<br>
My story Im ethical hacker please halpe me global  im leazy  and i need evrything is free  my asisten work for me i want hack any user name and password without any time west so please halpe me make for me evrything easy follow my heart  like magic install me automatic any android siting   i want evry thing without credit card login emale  another i dont have atime  so get start  i want  make new hacking application  like 1 click then  hack any thing so please halpe me world php ruby perl python

2021-05-13 16:38 UTC, merged

2026-09-06 15:28 UTC, lopezregalodelo-a11y reviewed
Updated

2026-09-06 15:28 UTC, lopezregalodelo-a11y approved these changes
Update

2026-09-06 15:28 UTC, lopezregalodelo-a11y requested changes
Updated

2026-10-10 11:02 UTC, stonersdash26 approved these changes

2026-10-14 15:16 UTC, stonersdash26 approved these changes