added shell cleaning trick
trimstray/the-book-of-secret-knowledge pull request #353
Opened 2022-02-28 17:27 UTC by caverav

I think that this trick could help some pentesters to get a comfortable shell.

2022-02-28 17:29 UTC, Sleekbobby1011 approved these changes

2022-02-28 20:34 UTC, merged

2022-04-15 06:14 UTC, bobcampbell112233 reviewed
Veery good tools

2022-05-16 13:01 UTC, Theanulbeed28 reviewed
[Dalvik](https://developers.facebook.com/docs/graph-api)

2022-05-23 20:21 UTC, Tingsook1981 commented
4507af97cbb5a31d948c58a62980f268e0054f03

2022-09-24 05:15 UTC, Spacesugarog commented
- [ ] uj u u

2022-12-04 05:13 UTC, Daddyzilla65 approved these changes

2023-03-26 01:58 UTC, Shinebest123 reviewed
Ghj

2023-04-13 21:13 UTC, TharealKey approved these changes

2023-06-14 05:48 UTC, Livingstone110 commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
```suggestion
- **[Shell One-liners](#shell-one-liners-toc)**
```

2023-06-14 05:48 UTC, Livingstone110 commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
README.md

2023-06-14 05:48 UTC, Livingstone110 commented on README.md
> +
README.md

2023-06-14 05:50 UTC, Livingstone110 commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
README.md

2023-06-14 07:01 UTC, Dirtyfaygo commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
Nice

2023-11-27 10:19 UTC, Gerrime commented
Boost volume

2023-12-16 20:57 UTC, porterjb commented
d30037f1671a853ab91a3e43a78c2f048b7b3ca2

2023-12-20 03:09 UTC, Lukasog222 reviewed
README.md

2023-12-20 03:14 UTC, Lukasog222 commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
README.md

2024-02-03 21:11 UTC, Skunkyducker approved these changes

2024-09-29 15:48 UTC, kiseCrow reviewed
Hello, can I use your code?

2024-09-29 15:50 UTC, kiseCrow commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
Is this comment blocked?

2024-09-30 03:53 UTC, Trujillo1G commented
Negative I don’t know what’s it for or anything.

On Sun, Sep 29, 2024 at 9:50 AM Darnelle George ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/trimstray/the-book-of-secret-knowledge/pull/353#discussion_r1780074639>
> :
>
> > @@ -114,8 +114,9 @@ Only main chapters:
>  - **[Hacking/Penetration Testing](#hackingpenetration-testing-toc)**
>  - **[Your daily knowledge and news](#your-daily-knowledge-and-news-toc)**
>  - **[Other Cheat Sheets](#other-cheat-sheets-toc)**
> -- **[One-liners](#one-liners-toc)**
> -- **[Shell functions](#shell-functions-toc)**
> +- **[Shell One-liners](#shell-one-liners-toc)**
>
> Is this comment blocked?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/trimstray/the-book-of-secret-knowledge/pull/353#discussion_r1780074639>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCUXNCYRSXGLFJ25XTQFNSTZZAOVTAVCNFSM5PRWVEB2U5DIOJSWCZC7NNSXTPCQOVWGYUTFOF2WK43UKJSXM2LFO45TEMZTGU4DQNBRGIYA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2024-12-06 19:09 UTC, Trujillo1G commented on README.md
> +- **[Shell Functions](#shell-functions-toc)**
Ok

2024-12-06 19:09 UTC, Trujillo1G commented on README.md
> -#### One-liners &nbsp;[<sup>[TOC]</sup>](#anger-table-of-contents)
Huh

2024-12-06 19:09 UTC, Trujillo1G commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
Ok

2024-12-06 19:09 UTC, Trujillo1G commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
Ok> README.md

2024-12-06 19:09 UTC, Trujillo1G commented on README.md
> -#### One-liners &nbsp;[<sup>[TOC]</sup>](#anger-table-of-contents)
Ok

2024-12-22 22:55 UTC, Dreday10 approved these changes

2024-12-22 23:32 UTC, Masw21 reviewed
Ok> README.md

2024-12-22 23:39 UTC, Masw21 reviewed
Ok> README.Md

2025-01-16 07:33 UTC, Scutua approved these changes

2025-01-24 23:42 UTC, Sholman81 reviewed
ty

2025-02-27 18:28 UTC, Hostitel commented
Ok👍

2025-03-06 09:59 UTC, Jorge-Martin777 reviewed
I approve

2025-03-06 10:07 UTC, Jorge-Martin777 approved these changes
Sudo

2025-03-06 10:07 UTC, Jorge-Martin777 commented on README.md
> -- **[Shell functions](#shell-functions-toc)**
#shell function sudo close all ports, front and end toc

2025-03-06 10:35 UTC, Jorge-Martin777 requested changes
Update Read

2025-06-19 14:25 UTC, maxpayne66613 approved these changes

2025-07-30 10:43 UTC, boltenstanley-hub22 approved these changes

2025-08-19 10:35 UTC, Lmillan12co approved these changes

2025-08-19 10:36 UTC, Lmillan12co approved these changes

2025-10-06 19:14 UTC, chrisboley53-debug approved these changes

2025-10-14 13:52 UTC, boltenstanley-hub22 commented
Okay so how do we go ahead

On Mon, 6 Oct 2025, 20:15 chrisboley53-debug, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/trimstray/the-book-of-secret-knowledge/pull/353#pullrequestreview-3306744847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BVKH42FUBHM3KESQDIRLMIT3WK5UFAVCNFSM5PRWVEB2U5DIOJSWCZC7NNSXTPCQOVWGYUTFOF2WK43UKJSXM2LFO45TGMZQGY3TINBYGQ3Q>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2025-10-17 22:42 UTC, Lmillan12co approved these changes

2025-10-27 18:30 UTC, LaColombe210 commented on README.md
> +- **[Shell One-liners](#shell-one-liners-toc)**
Q: how do I find things linked to me

2025-11-23 23:51 UTC, mabdollahi1379-arch commented on README.md
> -- **[Shell functions](#shell-functions-toc)**
q

2025-11-23 23:54 UTC, boltenstanley-hub22 commented on README.md
> -- **[Shell functions](#shell-functions-toc)**
#execute

2025-11-24 07:19 UTC, teremuhamblin approved these changes

2025-12-21 22:45 UTC, mabdollahi1379-arch reviewed
tnx

2025-12-21 23:55 UTC, mabdollahi1379-arch reviewed
tnxs

2026-01-11 07:01 UTC, sowja293 reviewed
May beee

2026-01-11 08:50 UTC, drpsykkjoker approved these changes

2026-02-03 19:29 UTC, corkumandrew557-tech approved these changes

2026-03-16 01:28 UTC, UnknownNameL7 approved these changes

2026-09-06 15:23 UTC, lopezregalodelo-a11y reviewed
Updated

2026-09-06 15:23 UTC, lopezregalodelo-a11y approved these changes
Updated

2026-09-06 15:24 UTC, lopezregalodelo-a11y requested changes
Updated

2026-09-06 18:53 UTC, boltenstanley-hub22 commented
Okay

On Sun, Sep 6, 2026, 4:24 PM lopezregalodelo-a11y ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Updated
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/trimstray/the-book-of-secret-knowledge/pull/353?email_source=notifications&email_token=BVKH42HFGKQB35LFNQHSR735NV6TFA5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMJSGU3TQNRZHEYKM4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#pullrequestreview-5125786990>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BVKH42BBR3WGZHPV5DNG3LD5NV6TFAVCNFSNUABFKJSXA33TNF2G64TZHMYTGOBTHEZTCMZZHNEXG43VMU5TCMJVGQZTMMJSGI42C5QC>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***
> com>
>

2026-09-06 18:57 UTC, boltenstanley-hub22 commented
Rub a tiny amount of mineral oil or baby oil after it's completely dry. It
really brings back the color.


On Sun, Sep 6, 2026, 7:52 PM Stanley bolten ***@***.***> wrote:

> Okay
>
> On Sun, Sep 6, 2026, 4:24 PM lopezregalodelo-a11y <
> ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Updated
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/trimstray/the-book-of-secret-knowledge/pull/353?email_source=notifications&email_token=BVKH42HFGKQB35LFNQHSR735NV6TFA5CNFSNUABKM5UWIORPF5TWS5BNNB2WEL2QOVWGYUTFOF2WK43UKJSXM2LFO4XTKMJSGU3TQNRZHEYKM4TFMFZW63VHMNXW23LFNZ2KKZLWMVXHJLDGN5XXIZLSL5RWY2LDNM#pullrequestreview-5125786990>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BVKH42BBR3WGZHPV5DNG3LD5NV6TFAVCNFSNUABFKJSXA33TNF2G64TZHMYTGOBTHEZTCMZZHNEXG43VMU5TCMJVGQZTMMJSGI42C5QC>
>> .
>> You are receiving this because you commented.Message ID:
>> ***@***.***
>> .com>
>>
>

2026-10-07 20:49 UTC, melitahambasic43-afk approved these changes

2026-10-07 20:50 UTC, melitahambasic43-afk commented
![a4615edded7eec77ddc74072975b9b30.jpg](https://github.com/user-attachments/assets/d2114dd1-9ffe-48e9-96b7-94e48157c817)

2026-10-08 02:31 UTC, hmadamas71-pixel commented
Thanks all

2026-10-08 18:41 UTC, stonersdash26 approved these changes

2026-10-10 10:59 UTC, stonersdash26 approved these changes

2026-10-10 10:59 UTC, stonersdash26 approved these changes

2026-10-13 08:23 UTC, stonersdash26 approved these changes

2026-10-14 20:15 UTC, Legacy-netizen commented
💀💀💀

2026-10-28 16:18 UTC, melitahambasic43-afk commented
- - [ ] - [ ] # - ** meĵlitahambasic **![9604428c760211182218e773b9b05f99.jpg](https://github.com/user-attachments/assets/d8bde044-5763-4b33-ab48-10137b1280a2)

2026-11-03 19:12 UTC, melitahambasic43-afk commented
![IMG_20261103_145859.jpg](https://github.com/user-attachments/assets/4413e06e-81c8-4371-9759-18e422b2ef32)

2026-11-07 09:55 UTC, melitahambasic43-afk commented
![IMG_20261105_174409.jpg](https://github.com/user-attachments/assets/b018fa35-a63b-4865-a472-386fe9207efa)

2026-11-07 09:56 UTC, melitahambasic43-afk approved these changes