Add Privacy Respecting DNS Server
trimstray/the-book-of-secret-knowledge pull request #357
Opened 2022-03-30 18:07 UTC by cosmicqbit

Added another Privacy focused DNS Server `9.9.9.9` by [Quad9](https://www.quad9.net/) to the existing list.

2022-04-04 16:32 UTC, Lindalu79 requested changes
O

2022-04-04 16:32 UTC, Lindalu79 commented on README.md
>  ###### TOP Browser extensions
.

2022-04-06 01:04 UTC, Zyarasa commented
Our a legend with love your hard work thank you sir please continue to illuminate the darkness

2022-04-18 04:24 UTC, 89118705066 approved these changes

2022-05-27 06:01 UTC, edgarelsalto requested changes
Gracias

2022-06-10 04:12 UTC, FukYaMudda approved these changes

2023-08-11 09:52 UTC, Samsongs10e requested changes
[

2023-11-24 17:46 UTC, skydiver1980 approved these changes

2024-06-11 01:55 UTC, KiseCrow approved these changes

2025-12-20 06:52 UTC, duartelalo11-stack commented on README.md
>  ###### TOP Browser extensions
Ok

2025-12-20 06:52 UTC, duartelalo11-stack commented on README.md
>  ###### TOP Browser extensions
Ok

2025-12-23 14:16 UTC, duartelalo11-stack commented on README.md
>  ###### TOP Browser extensions
How can I get off  off some people Who are inside my  pjone all the time?

2025-12-23 14:16 UTC, duartelalo11-stack commented on README.md
>  ###### TOP Browser extensions
How can I get off  off some people Who are inside my  pjone all the time?

2026-05-03 03:20 UTC, closed without merging