Added CLI tools: Yakuake, k9s and lazygit.
trimstray/the-book-of-secret-knowledge pull request #396
Opened 2023-04-13 07:52 UTC by MLengl

Added different CLI tools i am using daily as developer:

- Yakuake: Is a console emulator that makes you terminal always active and pop up your screen pressing F12. It can open multiple different shells, define base paths, customized in colors/transparency, ... and is always very usefull fot switching to the terminal very fast. It is a KDE tool but can be used everywhere meanwhile.
- k9s: is a full kubernetes manager using just the terminal. It has a powerfgul UI, nice intuitive shortcuts and it makes you managing (monitor/edit/switch/...) your clusters very fast. Ofcasue it needs kubectl/az-cli/... as dependency for appling the usual commands. It simply gives them a nice UI and makes it super simple to use.
- lazygit is a full GIT UI inside the terminal. It can be customized on themes, branch colors, .. and wraps up everything nicely. Your full git management it always accessable on your CLI sessions so you never need to leave the terminal again. (X = menu key and your best friend on starting/trying out)

2023-04-13 21:11 UTC, TharealKey approved these changes

2023-05-09 14:51 UTC, Bigdoe41 approved these changes

2023-05-10 17:59 UTC, Khechani reviewed
Khechani****

2023-05-10 18:21 UTC, Royettesean commented
> Khechani****

?

2023-05-15 09:29 UTC, celebritygoddes approved these changes

2023-05-15 09:32 UTC, stonerp32 commented
Sent from Yahoo Mail for iPhone


On Tuesday, May 9, 2023, 15:52, Bigdoe41 ***@***.***> wrote:




@Bigdoe41 approved this pull request.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-05-15 12:13 UTC, Khechani approved these changes

2023-05-15 12:13 UTC, Khechani approved these changes

2023-05-16 12:12 UTC, Bigdoe41 approved these changes

2023-11-24 17:41 UTC, skydiver1980 approved these changes

2024-01-02 12:17 UTC, emergencyusaarmyvaccation approved these changes

2024-01-28 16:15 UTC, Darthtimothy14 approved these changes

2024-01-28 16:15 UTC, Darthtimothy14 commented on README.md
>  &nbsp;&nbsp;:small_orange_diamond: <a href="https://github.com/peikk0/tmux-cssh"><b>tmux-cssh</b></a> - is a tool to set comfortable and easy to use functionality, clustering and synchronizing tmux-s
Install pkk

2024-01-28 16:15 UTC, Darthtimothy14 commented on README.md
> +&nbsp;&nbsp;:small_orange_diamond: <a href="https://github.com/derailed/k9s"><b>k9s</b></a> - is a full kubernetes (k8) manager that provides a UI inside your terminal.<br>
Install pkg

2024-01-28 16:15 UTC, Darthtimothy14 commented on README.md
> +&nbsp;&nbsp;:small_orange_diamond: <a href="https://github.com/KDE/yakuake"><b>yakuake</b></a> - is a highly customizeable terminal emulator that makes your terminal always accessable as popup window
https://github.com/oh-my-fish/oh-my-fish

2024-01-28 17:57 UTC, benchi133 commented on README.md
>  &nbsp;&nbsp;:small_orange_diamond: <a href="https://github.com/peikk0/tmux-cssh"><b>tmux-cssh</b></a> - is a tool to set comfortable and easy to use functionality, clustering and synchronizing tmux-s
Estoy en ello

2024-02-04 13:24 UTC, benchi133 requested changes
Me está controlando

2025-01-20 12:52 UTC, littlefoot27 approved these changes

2025-01-20 12:55 UTC, littlefoot27 approved these changes

2025-05-06 03:55 UTC, lovmy1 approved these changes

2025-12-20 06:53 UTC, duartelalo11-stack approved these changes

2026-01-26 06:23 UTC, closed without merging