Update README.md: Added netcat oneliners for skype and colored chat
trimstray/the-book-of-secret-knowledge pull request #423
Opened 2024-03-27 22:34 UTC by ErezBinyamin

2024-04-27 19:42 UTC, A1exKH requested changes
In title I can see "Skype", in PR code I can't see anything about it.
Please update title and description about actual information for this PR.

2024-04-28 01:26 UTC, ErezBinyamin commented
Good point @A1exKH . I corrected the PR title to more appropriately align with the titles of the oneliner section titles

2024-05-15 01:07 UTC, ErezBinyamin commented
@A1exKH ; Anything else need to be done here before a merge? Happy to make any additional requested changes?

2024-06-16 08:30 UTC, Abhi7739309 approved these changes

2024-06-16 08:30 UTC, Abhi7739309 commented on README.md
> +		-tune zerolatency -y /dev/stdout \
F mastar in out

2024-06-19 23:40 UTC, ErezBinyamin commented on README.md
> +		-tune zerolatency -y /dev/stdout \
Sorry, not sure what you mean by "F mastar in out". Happy to discuss and make any changes you'd recommend

2024-06-20 06:44 UTC, Trippertucker commented on README.md
> +		-tune zerolatency -y /dev/stdout \
> Sorry, not sure what you mean by "F mastar in out". Happy to discuss and make any changes you'd recommend 

Don't be sorry A.(y) I. Certainly a.i.'nT tbh but lezbhonest aLL the rest b liars and all their slashed tyres be 3000x individually lit bushfires by motorbikes n Ga$LiGhT3r$ while we takinG over all the Real estate and Diners 😂

2024-06-20 06:52 UTC, Trippertucker commented on README.md
> +		-tune zerolatency -y /dev/stdout \
'cause (& a/effect) still is without a true choice to control ur instAbilitease to select, let alone have adequate wisdom to fathom and accept True Truth which is undeniably Spiritual of OriGinal OriGin and aLways ❤️❤️❤️ of perfeCt LOVE & always 💯💯💯 CORRECT so go ahead it's typical to not comprehend and weakly fearfully REJECT The ElecTED #KinGkiLLa

2024-06-20 09:22 UTC, ErezBinyamin commented on README.md
> +		-tune zerolatency -y /dev/stdout \
I will be honest, I'm not sorry. While I agree with you about the liars and the bushfires, and the lack of free will inherent in causality... that's not in scope for this contribution. I cannot solve these problems with one line of bash. Unfortunately the best I can do is a two way video call. Perhaps in my next contribution I can address our mutual lack of freedom

2024-06-27 09:42 UTC, Dickerz approved these changes

2024-06-27 09:54 UTC, Dickerz approved these changes

2024-07-14 01:01 UTC, ErezBinyamin commented
@Trippertucker @A1exKH any thoughts on approving this?

2024-07-16 12:37 UTC, A1exKH approved these changes
LGTM.

2024-07-16 13:36 UTC, Abhi7739309 commented
LGTM KN

2024-08-09 03:31 UTC, ErezBinyamin commented
@Trippertucker any changes recommended?

2024-08-09 03:56 UTC, Abhi7739309 commented
https://github.com/trimstray/the-book-of-secret-knowledge/pull/423#issuecomment-2277075465

2024-08-10 00:32 UTC, Dickerz approved these changes

2024-08-10 00:38 UTC, ErezBinyamin commented
Is there a way to move on and approve without @Trippertucker ?

2024-12-08 20:46 UTC, ErezBinyamin commented
@Abhi7739309  @A1exKH @Dickerz  are any of you in contact with @Trippertucker ?? I'd like for this contribution to be merged. I was really hoping to be able to add something here

2024-12-22 10:38 UTC, 12-1012 approved these changes

2025-02-12 13:02 UTC, ErezBinyamin commented
Please remove @Trippertucker from required reviewers

2025-03-15 02:05 UTC, ErezBinyamin commented
Please remove @Trippertucker from required reviewers

2025-04-06 17:21 UTC, closed without merging