Update deprecated resource
trimstray/the-book-of-secret-knowledge pull request #431
Opened 2024-05-25 11:36 UTC by Mathu-lmn

As explained in the previous resource [Readme](https://github.com/skx/sysadmin-util#sysadmin-utils), the resource got replaced by a new one, that is kept up to date by its author !

2024-05-26 10:30 UTC, IcyGrllexx approved these changes

2024-05-29 04:33 UTC, Masterkush2009 approved these changes

2024-05-29 04:33 UTC, Masterkush2009 commented on README.md
> +&nbsp;&nbsp; <a href="https://github.com/skx/sysbox"><b>SysBox</b></a> - tools for Linux/Unix sysadmins.<br>
Start

2024-06-01 11:28 UTC, danielCalbonero12345 commented on README.md
> +&nbsp;&nbsp; <a href="https://github.com/skx/sysbox"><b>SysBox</b></a> - tools for Linux/Unix sysadmins.<br>
Hello

2024-06-02 12:55 UTC, kwang8282 approved these changes

2024-06-03 09:13 UTC, Eldo420 commented
It seems like you're referencing a GitHub issue in the repository `trimstray/the-book-of-secret-knowledge`. The issue number is 431, and it's about updating a deprecated resource. Here's a more detailed breakdown based on typical GitHub usage:

### Issue Information:
- **Repository**: `trimstray/the-book-of-secret-knowledge`
- **Issue Number**: 431
- **Title**: Update deprecated resource
- **Status**: Open
- **Branch**: master

### What You Can Do
If you want to contribute to resolving this issue, here is a step-by-step guide:

#### 1. Fork the Repository
Go to the [GitHub repository](https://github.com/trimstray/the-book-of-secret-knowledge) and fork it to your account.

#### 2. Clone the Repository
Clone the forked repository to your local machine.
```sh
git clone https://github.com/your-username/the-book-of-secret-knowledge.git
cd the-book-of-secret-knowledge
```

#### 3. Create a New Branch
Create a new branch for your changes.
```sh
git checkout -b update-deprecated-resource
```

#### 4. Update the Deprecated Resource
Locate the deprecated resource that needs updating. This could involve editing configuration files, code, or documentation.

#### 5. Commit Your Changes
Commit the changes with a meaningful commit message.
```sh
git add .
git commit -m "Update deprecated resource in accordance with issue #431"
```

#### 6. Push to Your Fork
Push the changes to your fork.
```sh
git push origin update-deprecated-resource
```

#### 7. Create a Pull Request
Go to the original repository and create a pull request from your forked repository. Ensure you reference the issue number in your pull request description.

### Example Pull Request Description:
```markdown
### Summary
This pull request addresses issue #431 by updating the deprecated resource.

### Changes Made
- Updated the resource in `file-path/resource-file`
- Modified relevant documentation
- Ensured compatibility with existing resources

### Verification
- [ ] Ran local tests
- [ ] Verified with the latest project version
```

After creating the pull request, the repository maintainers will review your changes and, after any necessary discussions or revisions, merge them into the master branch. This will resolve issue #431.

If you need more specific details on what resource needs updating, usually, the issue description or comments section provides further context, so make sure to review those carefully.

2024-06-05 21:56 UTC, CarlosA1610 commented on README.md
> +&nbsp;&nbsp; <a href="https://github.com/skx/sysbox"><b>SysBox</b></a> - tools for Linux/Unix sysadmins.<br>
# - [ ] # - [ ] - @[]()_**~~~~~~~~**_

2024-06-05 21:58 UTC, CarlosA1610 commented on README.md
> +&nbsp;&nbsp; <a href="https://github.com/skx/sysbox"><b>SysBox</b></a> - tools for Linux/Unix sysadmins.<br>
- - []()**~~~~**

2024-06-06 09:38 UTC, elsisi33 commented
> As explained in the previous resource [Readme](https://github.com/skx/sysadmin-util#sysadmin-utils), the resource got replaced by a new one, that is kept up to date by its author !

2024-06-10 03:04 UTC, REBELminds249 commented
J

2024-06-10 03:04 UTC, REBELminds249 approved these changes

2024-06-10 07:20 UTC, KiseCrow approved these changes

2024-06-11 00:01 UTC, Thaianzzzz requested changes
# installs nvm (Node Version Manager)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

# download and install Node.js (you may need to restart the terminal)
nvm install 20

# verifies the right Node.js version is in the environment
node -v # should print `v20.14.0`

# verifies the right NPM version is in the environment
npm -v # should print `10.7.0`

2024-06-12 02:40 UTC, KiseCrow commented on README.md
> +&nbsp;&nbsp; <a href="https://github.com/skx/sysbox"><b>SysBox</b></a> - tools for Linux/Unix sysadmins.<br>
Z-

2024-06-12 02:43 UTC, KiseCrow commented
Z-

2024-06-15 13:24 UTC, KiseCrow approved these changes

2024-06-15 13:24 UTC, KiseCrow approved these changes
Looks good

2024-06-15 13:38 UTC, KiseCrow commented
Ok.

2024-06-15 13:39 UTC, KiseCrow approved these changes

2024-06-15 13:40 UTC, KiseCrow approved these changes

2024-06-15 13:47 UTC, KiseCrow approved these changes

2024-06-15 13:47 UTC, KiseCrow commented on README.md
-z

2024-06-15 13:47 UTC, KiseCrow approved these changes

2024-06-15 14:40 UTC, KiseCrow approved these changes

2024-06-15 14:41 UTC, KiseCrow approved these changes

2024-06-15 15:32 UTC, KiseCrow approved these changes
Learning faster now.

2024-06-15 15:38 UTC, KiseCrow approved these changes

2024-06-16 15:59 UTC, Mathu-lmn commented
@trimstray Hey, can you look into this simple PR asap please !

2024-06-20 09:05 UTC, kiseCrow approved these changes

2024-06-20 09:06 UTC, kiseCrow commented on README.md
Ok

2024-06-20 09:07 UTC, kiseCrow approved these changes

2024-06-20 13:26 UTC, Atla224 approved these changes

2024-06-20 13:26 UTC, Atla224 commented on README.md
> -z

2024-07-10 09:10 UTC, yenaingtun-dev approved these changes

2024-07-11 07:21 UTC, ajmalasaru commented
Thank you

2024-08-09 01:39 UTC, Jackson-gold-oss commented on README.md
Hey 👋

2024-08-09 01:39 UTC, Jackson-gold-oss approved these changes

2024-10-22 01:09 UTC, DavidHaid292 reviewed
Thanks?

2025-03-23 19:16 UTC, canyavuz01 approved these changes

2025-05-19 03:44 UTC, nareshrajkumar866 approved these changes

2025-05-24 12:43 UTC, closed without merging