Added Hudson Rock to Passwords and Geeky Vendor Blogs
trimstray/the-book-of-secret-knowledge pull request #452
Opened 2024-12-22 13:04 UTC by hudsonrock-partnerships

- **Passwords** section update - added free cybercrime intelligence toolkit to check if an email address or domain was involved in an Infostealer malware attack.

- **Geeky Vendor Blogs** section update - added a dedicated hub with recent news about Infostealer malware.

2024-12-28 09:04 UTC, Jovelyn08 approved these changes

2025-01-06 04:54 UTC, Lurigt approved these changes

2025-01-25 04:08 UTC, zexko3-begzuw-vosnuZ approved these changes

2025-01-29 09:21 UTC, Lurigt reviewed
B

2025-01-29 11:51 UTC, teremuhamblin commented
Thanks for sharing

2025-02-02 23:03 UTC, Chiassonastraypatrick approved these changes

2025-02-25 05:32 UTC, sozoops approved these changes

2025-06-08 23:40 UTC, numan4597 commented
khansabreen7908@gmail.com  gmail password genreted

2025-06-09 02:50 UTC, andrewswan123 commented
[Export-6622d7ab-a20b-46ad-bdf8-0f779d6bb893.zip](https://github.com/user-attachments/files/20648547/Export-6622d7ab-a20b-46ad-bdf8-0f779d6bb893.zip)

2025-06-09 02:51 UTC, andrewswan123 commented
https://github.com/trimstray/the-book-of-secret-knowledge/pull/452#issuecomment-2954333526

2025-06-09 13:42 UTC, numan4597 requested changes
Show me password

2025-06-10 19:57 UTC, Machoalfa28 commented
I need you to stop bothering me once and for all or you will face legal action.
Sent from [Proton Mail](https://proton.me/mail/home) for iOS

El dom, 8 jun, 2025 a las 4:44 p.m., numan4597 ***@***.***(mailto:El dom, 8 jun, 2025 a las 4:44 p.m., numan4597 <<a href=)> escribió:

> numan4597 left a comment [(trimstray/the-book-of-secret-knowledge#452)](https://github.com/trimstray/the-book-of-secret-knowledge/pull/452#issuecomment-2954333526)
>
> ***@***.*** gmail password genreted
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/trimstray/the-book-of-secret-knowledge/pull/452#issuecomment-2954333526), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/BJ4IGFWFFCJ24CQKL5KJRIT3CTDG7AVCNFSM6AAAAABUBUHUB2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSNJUGMZTGNJSGY).
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2025-06-11 03:00 UTC, closed without merging